#!/usr/bin/env bash
set -euo pipefail

python3 tests/survey/test_serial_first_identity.py
python3 tests/survey/test_cybernet_cleanup_report.py
python3 Tests/survey/test_ad_probe_resilience_contracts.py
python3 Tests/survey/test_ad_existence_bulk_contracts.py
python3 Tests/survey/test_serial_network_preflight_contracts.py
python3 Tests/survey/test_probe_socket_access_contracts.py
python3 Tests/survey/test_standard_corporate_tooling_contracts.py
python3 Tests/survey/test_hotfix_command_registry_contracts.py
python3 Tests/survey/test_cybernet_com_qr_pack_contracts.py
python3 Tests/survey/test_checkpoint_discipline_contracts.py
python3 Tests/survey/test_local_harness_contracts.py
python3 Tests/survey/test_software_install_harness_contracts.py
python3 Tests/survey/test_run_context_contracts.py
bash Tests/bash/test_target_reduction_plan_contracts.sh
